name: "07 check run event"

permissions:
  checks: read       # Para leer los datos del check_run
  pull-requests: write # Si quieres comentar en el PR basado en ese check

on:
  check_run:
    types: [completed] # Se dispara al hacer clic en un botón personalizado

jobs:
  ejecutar_accion:
    runs-on: ubuntu-latest
    
    steps:
      - name: say hi
        run: |
          echo "se completo el check_run lint"
          
