name: "07 check run event"

on:
  check_run:
    types: [completed] # Se dispara al hacer clic en un botón personalizado

jobs:
  ejecutar_accion:
    if: ${{ github.event.check_run.name == 'lint'}}
    runs-on: ubuntu-latest
    
    steps:
      - name: say hi
        run: |
          echo "se completo el check_run lint"
          
