name: "07 check run event"

on:
  check_run:
    types: [requested_action] # Se dispara al hacer clic en un botón personalizado

jobs:
  ejecutar_accion:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Simulando Corrección DevOps
        run: |
          echo "Ejecutando parche de seguridad solicitado por el usuario..."
          echo "Check Run ID: ${{ github.event.check_run.id }}"
